spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/productinformation
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true  # 쿼리가 한줄이 아닌 포맷되서 가독성 증가

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
logging.level:
  org.hibernate.SQL: debug
  #  org.hibernate.type: trace